FROM node:22-alpine

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

COPY package*.json ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_API_URL=http://127.0.0.1:8001
ARG NEXT_PUBLIC_ORGANIZATION_EMAIL_DOMAIN=
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_ORGANIZATION_EMAIL_DOMAIN=$NEXT_PUBLIC_ORGANIZATION_EMAIL_DOMAIN

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
