apiVersion: v1
kind: Namespace
metadata:
  name: calendar-frontend
  labels:
    app.kubernetes.io/part-of: calendar
    app.kubernetes.io/name: calendar-frontend
    app.kubernetes.io/component: frontend
