apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: calendar-frontend
    newName: mohankatari/calendar-frontend
    newTag: f17261e64922b56d1fa799b7af34eb89a58b0569
