apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: calendar-frontend
    newName: mohankatari/calendar-frontend
    newTag: fe1dc40c2c8b22f4e7e34b7839197ce16e71cc70
