apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: calendar-frontend
    newName: mohankatari/calendar-frontend
    newTag: bfe96a3158a4be097fdfb6176164a4fec83ec190
